config/routes.rb
Rails.application.routes.draw do
  resources :groups
  devise_for :users
  resources :users
resources :tweets
  root 'tweets#index'
get '/bootstrap', to: 'tweets#bootstrap'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
    class Group < ApplicationRecord
  has_many :users_groups
  has_many :users, -> { distinct }, through: :users_groups
  validates_presence_of :name
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
belongs_to :user
validates_presence_of :kontent
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
has_many :tweets
has_many :users_groups
has_many :groups,  -> { distinct }, through: :users_groups

accepts_nested_attributes_for :groups, :allow_destroy => true




end

app/models/users_group.rb
class UsersGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :description, :user_ids)
    end
end

app/controllers/tweets_controller.rb
    class TweetsController < ApplicationController
   before_action :set_tweet, only: [:show, :edit, :update, :destroy, :authorize]
   before_action :authorize, only:[:edit, :destroy]

  def index
    @tweets=Tweet.all
  end

  def show
    # binding.pry pAuza
  end

  def new
    @tweet=Tweet.new
  end

  def edit
  end


  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html {redirect_to @tweet}  #nie ma notice
      else
            format.html {render :edit}
      end
    end
  end


  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html {redirect_to @tweet}  #nie ma notice
      else 
        format.html {render :edit}
      end
    end
  end

  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def bootstrap 
    @user = User.first
  end

def authorize
    unless @tweet.user_id == current_user.id 
    flash[:notice] = "You are not the creator of this tweet, therefore you're not permitted to edit or destroy this tweet"
    redirect_to root_path # or anything you prefer
    return false # Important to let rails know that the controller should not be executed
  end
end



  private

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end


  def tweet_params
    params.require(:tweet).permit(:title, :kontent, :rejting, :user_id)   
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :authorize]
  before_action :authorize, only:[:edit, :destroy]



  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

##@user.groups.build # build ingredient attributes, nothing new here

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

def authorize
    unless @user.id == current_user.id 
    flash[:notice] = "You are not the creator of this user, therefore you're not permitted to edit or destroy this user"
    redirect_to users_path # or anything you prefer
    return false # Important to let rails know that the controller should not be executed
  end
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :bio, :age, :email, group_ids:[])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.html.erb
<%= form_for(group) do |f| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
 <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" <%= link_to 'Home', tweets_path %></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to 'Users', users_path %></li>
            <li class="active"><%= link_to 'Groups', groups_path %></li>
            <li class="active"><%= link_to "Bootstrap", '/bootstrap', :method => :get%></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> </li>                
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Session Control</li>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
               </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>



<h1 class="index-header">
  <div class="col-md-12 text-center">
  <label class="label label-default">Groups</label>
</div>
</h1>

<table class="table">  
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>User names</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.description %></td>
        <td class="label label-info"><%= group.users.pluck(:name).join(' ') %></td>
          
        <td><%= link_to 'Show', group, class: 'btn btn-xs btn-warning' %> </td>
        <td><%= link_to 'Edit', edit_group_path(group), class: 'btn btn-xs btn-info' %> </td>
        <td><%= link_to 'Destroy', group, method: :delete, class: 'btn btn-xs btn-danger'%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

 <div class="col-md-12 text-center"><%= link_to 'New Group', new_group_path, class: 'btn btn-sm btn-primary' %></div>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @group.description %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitterqq</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


<% if notice %>                                       
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>




<!-- <p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %> -->






    <%= yield %>
  </body>
</html>

app/views/tweets/_form.html.erb
   
  <%= form_for(tweet) do |f| %>

    <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
   </div>

  <div class="field">
    <%= f.label :kontent %>
    <%= f.text_area :kontent %>
   </div>

  <div class="field">
    <%= f.label :rejting %>
    <%= f.number_field :rejting %>
   </div>

 <div class="field">
    <%= f.hidden_field :user_id, value: current_user.id %>
   </div>   

 <div class="actions">
  <%=  f.submit %>
 </div>

 <% end %>

app/views/tweets/edit.html.erb
<%= @tweet.errors.full_messages.first if @tweet.errors.any? %>


<h1> Editing Tweet </h1>



<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %>
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
  <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" <%= link_to 'Home', tweets_path %></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to 'Users', users_path %></li>
            <li class="active"><%= link_to 'Groups', groups_path %></li>
            <li class="active"><%= link_to "Bootstrap", '/bootstrap', :method => :get%></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> </li>                
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Session Control</li>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
               </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>


    
<p>



<h1 class="index-header">
  <div class="col-md-12 text-center">
  <label class="label label-default">Tweets</label>
  </div>
</h1>


      </div>
      <div class="row">
        <div class="col-md-12">
         <table class="table">
            <thead>
              <tr>
      <th>Created</th>
      <th>Updated</th>
      <th>Title</th>
      <th>Kontent</th>
      <th>Rejting</th>
      <th>User</th>
              </tr>
            </thead>
         <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.created_at %></td>
        <td><%= tweet.updated_at %></td>
        <td><%= tweet.title %></td>
        <td><%= tweet.kontent %></td>
        <td><%= tweet.rejting %></td>

<td>
 <% if tweet.user.present? %>
   <%= link_to tweet.user.name, tweet.user, class: 'btn btn btn-primary' %>
 <%end%>
   
</td>


        <td><%= link_to 'Show', tweet, class: 'btn btn-xs btn-warning' %> </td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet), class: 'btn btn-xs btn-info' %> </td>
        <td><%= link_to 'Destroy', tweet, method: :delete, class: 'btn btn-xs btn-danger'%></td>
      </tr>
    <% end %>
  </tbody>
          </table>
        </div>

<br>

<div class="container">
 <div class="row">

 <div class="col-md-12 text-center"><%= link_to 'New Tweet', new_tweet_path, class: 'btn btn-sm btn-primary' %></div>

</div>
</div>

  

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p>
 <strong>Title:</strong>
 <%= @tweet.title %>
</p>

<p>
 <strong>Kontent:</strong>
 <%= @tweet.kontent %>
</p>

<p>
 <strong>Rejting:</strong>
 <%= @tweet.rejting %>
</p>

<p>
 <strong>User name:</strong>
 <% if @tweet.user.present? %>
 <%= @tweet.user.name %> 
   <% else %>
    <%= 'No user'  %>
 <% end %>
</p>


<%= link_to 'Edit', edit_tweet_path(@tweet), class: 'btn btn-xs btn-info'%> |
<%= link_to 'Back', tweets_path, class: 'btn btn-xs btn-primary' %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :bio %>
    <%= f.text_area :bio %>
  </div>

  <div class="field">
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

 

  
 

<div class="field">
  <%= f.label "Group" %><br />
  <%= f.collection_check_boxes :group_ids, Group.all, :id, :name do |b| %>
    <div class="collection-check-box">
      <%= b.check_box %>
      <%= b.label %>
    </div>
  <% end %>
</div>
  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
 <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" <%= link_to 'Home', tweets_path %></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to 'Users', users_path %></li>
            <li class="active"><%= link_to 'Groups', groups_path %></li>
            <li class="active"><%= link_to "Bootstrap", '/bootstrap', :method => :get%></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> </li>                
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Session Control</li>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
               </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>



  <p>
<h1 class="index-header">                                                    
  <div class="col-md-12 text-center">
  <label class="label label-default">Users</label>
</div>
</h1>

      </div>
      <div class="row">
        <div class="col-md-12">
            <table class="table">
            <thead>
              <tr>
      <th>Name</th>
      <th>Bio</th>
      <th>Age</th>
      <th>Email</th>
      <th>Ilość tweetow</th>
      <th>Id grup</th>

             </tr>
            </thead>
 <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.bio %></td>
        <td><%= user.age %></td>
        <td><%= user.email %></td>
         <td><% if user.tweets.any?%>
           <%= user.tweets.count %>
                             
         <% end %></td>
        <td class="label label-info"><%= user.groups.pluck(:name).join(' ') %></td>
        <td><%= link_to 'Show', user , class: 'btn btn-xs btn-warning'%></td>
        <td><%= link_to 'Edit', edit_user_path(user) , class: 'btn btn-xs btn-info'%></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
          </table>
        </div>




</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @user.bio %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Tweets:</strong>
  <%= @user.tweets.count %>

</p>

<p>
  <strong>Groups:</strong>
  <%= @user.groups.count %>

</p>

<p>
  <div class="col-md-12 text-center">
 <h3><label class="label label-default">Tweets</label></h3>
</div>
 </p>
  <div class="row">
        <div class="col-md-12">
          <table class="table">
  <thead>
 <p>
  <tr>
      <th>Title</th>
      <th>Kontent</th>
      <th>Rejting</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>
 
    <tr>
  <% @user.tweets.each do |tweet| if @user.tweets.any? %>
      
        <td><%= tweet.title %></td>
        <td><%= tweet.kontent %></td>
        <td><%= tweet.rejting %></td>
      </tr>
           </p>    
  <% end %>
  <% end %>
</table>


<%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-xs btn-info'%> |
<%= link_to 'Back', users_path, class: 'btn btn-xs btn-primary' %>

 